export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_WASHLIST = "ADD_TO_WASHLIST";
export const REMOVE_FROM_WASHLIST = 'REMOVE_FROM_WASHLIST';